# Example configuration for UI customization
# This file demonstrates how to configure the user menu, social links, and custom menu items in Kafka UI

ui:
  # User menu configuration (appears at the bottom of left sidebar)
  userMenu:
    enabled: true  # Set to false to hide the user menu completely
    accountUrl: "https://iam.demo.m3.nexiona.io/realms/server/account"  # URL for the account page
    logoutUrl: "https://console.demo.m3.nexiona.io/oauth2/sign_out"  # URL for logout

  # Social links configuration (appears in the top right navbar)
  socialLinks:
    enabled: true  # Set to false to hide all social links
    githubUrl: "https://github.com/kafbat/kafka-ui"
    discordUrl: "https://discord.com/invite/4DWzD7pGE5"
    productHuntUrl: "https://producthunt.com/products/ui-for-apache-kafka"

  # Custom menu items configuration (appears in the left sidebar above the user menu)
  # Icons can be Font Awesome icon names (without prefix) or emojis
  customMenuItems:
    - label: "Scheduler"
      url: "https://wsl.ymbihq.local:3012"
      icon: "fa-clock"  # Font Awesome icon (will render as <FontAwesomeIcon icon={faClock} />)
    - label: "Monitoring"
      url: "https://monitoring.example.com"
      icon: "fa-chart-line"  # Another Font Awesome icon
    - label: "Documentation"
      url: "https://docs.example.com"
      icon: "📚"  # Emoji icon (will render as plain text)

# To disable user menu entirely:
# ui:
#   userMenu:
#     enabled: false

# To disable social links entirely:
# ui:
#   socialLinks:
#     enabled: false

# To customize only specific URLs (others will use defaults):
# ui:
#   socialLinks:
#     enabled: true
#     githubUrl: "https://github.com/your-org/your-repo"
#     # discordUrl and productHuntUrl will use default values

# Custom menu items with Font Awesome icons:
# Icon names should be Font Awesome icon names without the 'fa-' prefix
# Examples: "clock", "chart-line", "database", "server", "cog", "user", "bell"
# Full list: https://fontawesome.com/icons
